version: 1
disable_existing_loggers: True
open_logging_file: true

formatters:
    console_format:
        format: '%(name)s | %(levelname)s | %(module)s | %(filename)s | %(funcName)s | %(lineno)d | %(message)s'
    file_format:
        format: '%(asctime)s | %(name)s | %(levelname)s | %(module)s | %(filename)s | %(funcName)s | %(lineno)d | %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: WARNING
        formatter: console_format
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: file_format
        filename: C:\python_log\template.log
        mode: w

loggers:
    dev:
        level: DEBUG
        handlers: [console, file]
        propagate: no
    prod:
        level: WARNING
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]